version: '3.9'

services:
  cache:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - face_the_music_backend

  database:
    image: mongo
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    networks:
      - face_the_music_backend

  # mongo-express:
  #   image: mongo-express
  #   # restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example

networks:
  face_the_music_backend:
    driver: bridge
  # face_the_music_frontend:
  #   driver: bridge
