name: CI

on: [push, pull_request]

# env:
#   NODE_VERSION: '14.x'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          # node-version: ${{NODE_VERSION}}
          node-version: '15.x'

      - name: Cache modules
        id: getCache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('./yarn.lock') }}

      - name: Lock yarn file
        if: steps.getCache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile --non-interactive

      - name: Lint
        run: yarn lint

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          # node-version: ${{NODE_VERSION}}
          node-version: '15.x'

       - name: Cache modules
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('./yarn.lock') }}

      - name: Lock yarn file
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile --non-interactive

      - name: Build
        run: yarn build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          # node-version: ${{NODE_VERSION}}
          node-version: '15.x'

       - name: Cache modules
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('./yarn.lock') }}

      - name: Lock yarn file
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile --non-interactive

      - name: Test
        run: yarn test
